version: '3.8'

networks:
  docker-networks-symfony:

services:
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: ${APP_NAME}-php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - docker-networks-symfony

  mysql-service:
    image: mysql:8
    container_name: ${APP_NAME}-mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: ${DB_ROOT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - docker-networks-symfony

  nginx-service:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx-container
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - docker-networks-symfony
    restart: always